### ISSUE TITLE
User fixation

### ISSUE THREAD

**Issue by alvin-dotcom** [Adarsh3321/TIC-TAC-TOE------CSS#1]
Try to add a ai or computer as a secondary player to this game, which will make the game more engaging, and try to add a landing page too.

Looking forward to see your next project as a saas landing page with gsap (Try it out!!)

**Comment by Adarsh3321** [comment]
As the name suggest it is a purely CSS based TIC TAC TOE 
and what you are trying to incorporate here is not going to happen 
but for you ill make a new one with JS and all to meet your needs.
